#!/bin/bash

sfntedit -d kern Junicode-Italic-raw.ttf

makeotf -fi fontinfo -f Junicode-Italic-raw.ttf -o Junicode-Italic-new.ttf -ff Junicode-Italic.fea -mf JunicodeNameDB
if [ $? -ne 0 ]; then
    echo "makeotf error"
    exit
fi
echo "Running ttfautohint to produce Junicode-Italic.ttf . . ."
ttfautohint -v --reference=JunicodeBlueRef.otf Junicode-Italic-new.ttf Junicode-Italic.ttf
